# ASSIGNMENT-1

# WEB SCRAPING

In [1]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\programdata\anaconda3\lib\site-packages (0.0.1)

WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.26.0)

WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arso (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2021.10.8)

In [2]:
# importing the required libraries
from bs4 import BeautifulSoup
import requests

In [3]:
import pandas as pd

<b>1) Write a python program to display all the header tags from wikipedia.org.</b>

In [4]:
page = requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

soup = BeautifulSoup(page.content)
soup




Header_tags=[]
for i in soup.find_all('span', class_="mw-headline"):
    Header_tags.append(i.text)

In [5]:
Header_tags=pd.DataFrame({'Header_tags': Header_tags})
Header_tags

                     Header_tags
0           Welcome to Wikipedia
1  From today's featured article
2               Did you know ...
3                    In the news
4                    On this day
5       Today's featured picture
6       Other areas of Wikipedia
7    Wikipedia's sister projects
8            Wikipedia languages

<b>2) Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release)
and make data frame.</b>

In [6]:
page=requests.get('https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc')
page

soup=BeautifulSoup(page.content)
soup



name=[]
for i in soup.find_all('h3',class_="lister-item-header"):
    name.append(i.text[4:-8])



rating=[]
for i in soup.find_all('div',class_="ratings-bar"):
    rating.append(i.text[3:6]) 
    
    
    
year_of_release=[]
for i in soup.find_all('span',class_="lister-item-year text-muted unbold"):
    year_of_release.append(i.text[1:5])

In [7]:
IMDB_Top_rated_100_movies=pd.DataFrame({'Name':name,'Rating':rating,'Year_of_Release':year_of_release})
IMDB_Top_rated_100_movies

                                                 Name Rating Year_of_Release
0                            The Shawshank Redemption    9.3            1994
1                                       The Godfather    9.2            1972
2                                     The Dark Knight    9.0            2008
3       The Lord of the Rings: The Return of the King    9.0            2003
4                                    Schindler's List    9.0            1993
5                              The Godfather: Part II    9.0            1974
6                                        12 Angry Men    9.0            1957
7                                        Pulp Fiction    8.9            1994
8                                           Inception    8.8            2010
9             \nThe Lord of the Rings: The Two Towers    8.8            2002
10                                       \nFight Club    8.8            1999
11  \nThe Lord of the Rings: The Fellowship of the...    8.8            2001
12                                     \nForrest Gump    8.8            1994
13                  \nIl buono, il brutto, il cattivo    8.8            1966
14                                \nTop Gun: Maverick    8.7            2022
15                                       \nThe Matrix    8.7            1999
16                                       \nGoodfellas    8.7            1990
17                          \nThe Empire Strikes Back    8.7            1980
18                  \nOne Flew Over the Cuckoo's Nest    8.7            1975
19                                     \nInterstellar    8.6            2014
20                                   \nCidade de Deus    8.6            2002
21                    \nSen to Chihiro no kamikakushi    8.6            2001
22                              \nSaving Private Ryan    8.6            1998
23                                   \nThe Green Mile    8.6            1999
24                                  \nLa vita è bella    8.6            1997
25                                            \nSe7en    8.6            1995
26                       \nTerminator 2: Judgment Day    8.6            1991
27                         \nThe Silence of the Lambs    8.6            1991
28                                        \nStar Wars    8.6            1977
29                                          \nSeppuku    8.6            1962
30                             \nShichinin no samurai    8.6            1954
31                            \nIt's a Wonderful Life    8.6            1946
32                                     \nGisaengchung    8.5            2019
33                                         \nWhiplash    8.5            2014
34                                 \nThe Intouchables    8.5            2011
35                                     \nThe Prestige    8.5            2006
36                                     \nThe Departed    8.5            2006
37                                      \nThe Pianist    8.5            2002
38                                        \nGladiator    8.5            2000
39                               \nAmerican History X    8.5            1998
40                               \nThe Usual Suspects    8.5            1995
41                                             \nLéon    8.5            1994
42                                    \nThe Lion King    8.5            1994
43                            \nNuovo Cinema Paradiso    8.5            1988
44                                   \nHotaru no haka    8.5            1988
45                               \nBack to the Future    8.5            1985
46                                   \nApocalypse Now    8.5            1979
47                                            \nAlien    8.5            1979
48                     \nOnce Upon a Time in the West    8.5            1968
49                                           \nPsycho    8.5            1960

<b>3) Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year of
release) and make data frame.</b>

In [8]:
page=requests.get('https://www.imdb.com/india/top-rated-indian-movies/')
page

soup=BeautifulSoup(page.content)
soup



name=[]
for i in soup.find_all('td',class_='titleColumn'):
    name.append(i.text[12:-8])


    
rating=[]
for i in soup.find_all('td',class_="ratingColumn imdbRating"):
    rating.append(i.text[1:4])
    
    
    
year_of_release=[]
for i in soup.find_all('span',class_="secondaryInfo"):
    year_of_release.append(i.text[1:5])

In [9]:
IMDB_Top_rated_100_Indian_movies=pd.DataFrame({'Name':name,'Rating':rating,'Year_of_Release':year_of_release,})
IMDB_Top_rated_100_Indian_movies[:100]

                                 Name Rating Year_of_Release
0                            Jai Bhim    8.4            2021
1                          Anbe Sivam    8.4            2003
2                             Golmaal    8.4            1979
3                             Nayakan    8.4            1987
4                   Pariyerum Perumal    8.4            2018
..                                ...    ...             ...
95                             Masaan    8.0            2015
96                     Dil Chahta Hai    8.0            2001
97                            Kahaani    8.0            2012
98            Maheshinte Prathikaaram    8.0            2016
99        Baahubali 2: The Conclusion    8.0            2017

[100 rows x 3 columns]

<b>4) Write a python program to display list of respected former presidents of India(i.e. Name , Term of office)
from https://presidentofindia.nic.in/former-presidents.htm</b>

In [10]:
page=requests.get('https://presidentofindia.nic.in/former-presidents.htm')
page

soup=BeautifulSoup(page.content)
soup



name=[]
for i in soup.find_all('div',class_='presidentListing'):
    name.append(i.text.split("\n")[1])

name




term_of_office=[]
for i in soup.find_all("div", class_="presidentListing"):
     term_of_office.append(i.find_all("p")[0].text.split(":")[1])

In [11]:
Former_Presidents=pd.DataFrame({'Name':name,'Term of Office': term_of_office})
Former_Presidents

,Name,Term of Office
0,Shri Pranab Mukherjee (1935-2020),"25 July, 2012 to 25 July, 2017"
1,Smt Pratibha Devisingh Patil (birth - 1934),"25 July, 2007 to 25 July, 2012"
2,DR. A.P.J. Abdul Kalam (1931-2015),"25 July, 2002 to 25 July, 2007"
3,Shri K. R. Narayanan (1920 - 2005),"25 July, 1997 to 25 July, 2002"
4,Dr Shankar Dayal Sharma (1918-1999),"25 July, 1992 to 25 July, 1997"
5,Shri R Venkataraman (1910-2009),"25 July, 1987 to 25 July, 1992"
6,Giani Zail Singh (1916-1994),"25 July, 1982 to 25 July, 1987"
7,Shri Neelam Sanjiva Reddy (1913-1996),"25 July, 1977 to 25 July, 1982"
8,Dr. Fakhruddin Ali Ahmed (1905-1977),"24 August, 1974 to 11 February, 1977"
9,Shri Varahagiri Venkata Giri (1894-1980),"3 May, 1969 to 20 July, 1969 and 24 August, 1..."
10,Dr. Zakir Husain (1897-1969),"13 May, 1967 to 3 May, 1969"
11,Dr. Sarvepalli Radhakrishnan (1888-1975),"13 May, 1962 to 13 May, 1967"
12,Dr. Rajendra Prasad (1884-1963),"26 January, 1950 to 13 May, 1962"

<b>5) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:     
a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.        
b) Top 10 ODI Batsmen along with the records of their team and rating.     
c) Top 10 ODI bowlers along with the records of their team and rating.</b>

a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.

In [12]:
#Sending get request to webpage server to get the source code of it
page=requests.get("https://www.icc-cricket.com/rankings/mens/team-rankings/odi")
page

#Webpage source code
page.content

#Parsing the source code by using BeautifulSoup and by html.parser
soup=BeautifulSoup(page.content,'html.parser')
soup

#Extracting all the tags having team names
team=soup.find_all('span',class_="u-hide-phablet")
team[:10]

#Extracting the text alone from the tags
teams=[]  #Empty list
for i in team:
    teams.append(i.get_text())
teams[:10]

#Extracting the tags having the number of matches for Rank1 team
match=soup.find_all('td',class_="rankings-block__banner--matches")
match

#Saving matches to matches list
Matches=[]  
for i in match:
    Matches.append(i.get_text().replace('\n',''))
Matches

#Extracting remaining matches
match=soup.find_all('td',class_="table-body__cell u-center-text")
match[:9]

del match[1::2]   #As it extracted other column data, we are deleting it

for i in match:
    Matches.append(i.get_text().replace('\n',''))
Matches[:10]

#Extracting the tags having the points for Rank1 team
points=soup.find_all('td',class_="rankings-block__banner--points")
points

#Saving points to points list
Points=[]  
for i in points:
    Points.append(i.get_text().replace('\n',''))
Points

#Extracting remaining points
points=soup.find_all('td',class_="table-body__cell u-center-text")
points[:9]

del points[::2]   #As other data are obtained, we are deleting them

#Saving points of respective teams
for i in points:
    Points.append(i.get_text().replace('\n',''))
Points[:10]

#Extracting the rating from tags of rank1 team
rating=soup.find_all('td',class_="rankings-block__banner--rating u-text-right")
rating

#Saving rating to rating list
Rating=[]  
for i in rating:
    Rating.append(i.get_text().replace('\n','').strip())
Rating

#Extracting other team ratings data
rating=soup.find_all('td',attrs={'class':'table-body__cell u-text-right rating'})
rating[:9]

#Saving other teams ratings 
for i in rating:
    Rating.append(i.get_text().replace('\n',''))
Rating=Rating[0:10]   #Saving only first 10 ratings
Rating

#Checking the length of each of the list obtained
print(len(teams),len(Matches),len(Points),len(Rating))

#Creating a new dataframe with the data we extracted
import pandas as pd
Team_Rankings=pd.DataFrame({})
Team_Rankings['Team']=teams[:10]
Team_Rankings['Matches']=Matches[:10]
Team_Rankings['Points']=Points[:10]
Team_Rankings['Rating']=Rating

#Checking the dataframe
Team_Rankings

25 20 20 10

           Team Matches Points Rating
0   New Zealand      12  1,505    125
1       England      19  2,353    124
2     Australia      18  1,929    107
3         India      22  2,304    105
4      Pakistan      16  1,635    102
5  South Africa      19  1,872     99
6    Bangladesh      24  2,275     95
7     Sri Lanka      24  2,086     87
8   West Indies      26  1,885     73
9   Afghanistan      15    986     66

b) Top 10 ODI Batsmen in men along with the records of their team and rating.

In [13]:
#Sending get request to webpage server to get the source code of it
page=requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting")
page

#Webpage source code
page.content

#Parsing the source code by using BeautifulSoup and by html.parser
soup=BeautifulSoup(page.content,'html.parser')
soup

#Extracting the tag having player name for Rank1
name=soup.find_all('div',class_="rankings-block__banner--name-large")
name

#Extracting the text alone from tag
names=[]  #Empty list
for i in name:
    names.append(i.get_text())
names

#Extracting the tag having player names
name=soup.find_all('td',class_="table-body__cell rankings-table__name name")
name[:9]

#Extracting the text from tags
for i in name:
    names.append(i.get_text().replace('\n', ' '))
names[:10]    

#Extracting the tag for team for rank1
team=soup.find_all('div',class_="rankings-block__banner--nationality")
team

#Extracting the text alone from tag
teams=[]  #Empty list
for i in team:
    teams.append(i.get_text().replace('\n', ''))
teams   

#Extracting the tags for other teams
team=soup.find_all('span',class_="table-body__logo-text")
team[:9]

#Extracting the text alone from tags
for i in team:
    teams.append(i.get_text())
teams[:10] 

#Extracting the tag having rating for rank1
rating=soup.find_all('div',class_="rankings-block__banner--rating")
rating

#Extracting the text alone from tag
ratings=[]  #Empty list
for i in rating:
    ratings.append(i.get_text())
ratings 

#Extracting the tag for ratings of other players
rating=soup.find_all('td',class_="table-body__cell rating")
rating[:9]

#Extracting the text alone from tags
for i in rating:
    ratings.append(i.get_text())
ratings[:10] 

#Extracting the tags having career best rating for rank1
career_best=soup.find_all('span',class_="rankings-block__career-best-text")
career_best

#Extracting the text alone from tag
career_best_rating=[]  #Empty list
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('  ',''))
career_best_rating    

#Extracting the tags for remaining players career best rating
career_best=soup.find_all('td',class_="table-body__cell u-text-right u-hide-phablet")
career_best[:9]

#Extracting the text alone from tags
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('                        ',' '))
career_best_rating[:10] 

#Checking the length of each of the list obtained
print(len(names),len(teams),len(ratings),len(career_best_rating))

#Creating a new dataframe with the data we extracted
import pandas as pd
top10=pd.DataFrame({})
top10['Name']=names[:10]
top10['Team']=teams[:10]
top10['Rating']=ratings[:10]
top10['Career_best_rating']=career_best_rating[:10]

#Checking the dataframe
top10

100 100 100 100

,Name,Team,Rating,Career_best_rating
0,Babar Azam,PAK,891,"891 v Australia, 02/04/2022"
1,Virat Kohli,IND,811,"911 v England, 12/07/2018"
2,Imam-ul-Haq,PAK,795,"795 v Australia, 02/04/2022"
3,Rohit Sharma,IND,791,"885 v Sri Lanka, 06/07/2019"
4,Quinton de Kock,SA,789,"813 v Sri Lanka, 10/03/2019"
5,Jonny Bairstow,ENG,775,"796 v India, 26/03/2021"
6,Ross Taylor,NZ,775,"841 v Bangladesh, 05/06/2019"
7,Rassie van der Dussen,SA,769,"776 v Bangladesh, 20/03/2022"
8,David Warner,AUS,750,"880 v Pakistan, 26/01/2017"
9,Aaron Finch,AUS,745,"798 v England, 25/06/2019"

c) Top 10 ODI bowlers along with the records of their team and rating.

In [14]:
#Sending get request to webpage server to get the source code of it
page=requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling")
page

#Webpage source code
page.content

#Parsing the source code by using BeautifulSoup and by html.parser
soup=BeautifulSoup(page.content,'html.parser')
soup

#Extracting the tag having player name for Rank1
name=soup.find_all('div',class_="rankings-block__banner--name-large")
name

#Extracting the text alone from tag
names=[]  #Empty list
for i in name:
    names.append(i.get_text())
names

#Extracting the tag having player names
name=soup.find_all('td',class_="table-body__cell rankings-table__name name")
name[:9]

#Extracting the text from tags
for i in name:
    names.append(i.get_text().replace('\n', ' '))
names[:10]    

#Extracting the tag for team for rank1
team=soup.find_all('div',class_="rankings-block__banner--nationality")
team

#Extracting the text alone from tag
teams=[]  #Empty list
for i in team:
    teams.append(i.get_text().replace('\n', ''))
teams   

#Extracting the tags for other teams
team=soup.find_all('span',class_="table-body__logo-text")
team[:9]

#Extracting the text alone from tags
for i in team:
    teams.append(i.get_text())
teams[:10] 

#Extracting the tag having rating for rank1
rating=soup.find_all('div',class_="rankings-block__banner--rating")
rating

#Extracting the text alone from tag
ratings=[]  #Empty list
for i in rating:
    ratings.append(i.get_text())
ratings 

#Extracting the tag for ratings of other players
rating=soup.find_all('td',class_="table-body__cell rating")
rating[:9]

#Extracting the text alone from tags
for i in rating:
    ratings.append(i.get_text())
ratings[:10] 

#Extracting the tags having career best rating for rank1
career_best=soup.find_all('span',class_="rankings-block__career-best-text")
career_best

#Extracting the text alone from tag
career_best_rating=[]  #Empty list
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('  ',''))
career_best_rating    

#Extracting the tags for remaining players career best rating
career_best=soup.find_all('td',class_="table-body__cell u-text-right u-hide-phablet")
career_best[:9]

#Extracting the text alone from tags
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('                        ',' '))
career_best_rating[:10] 

#Checking the length of each of the list obtained
print(len(names),len(teams),len(ratings),len(career_best_rating))

#Creating a new dataframe with the data we extracted
import pandas as pd
top10=pd.DataFrame({})
top10['Name']=names[:10]
top10['Team']=teams[:10]
top10['Rating']=ratings[:10]
top10['Career_best_rating']=career_best_rating[:10]

#Checking the dataframe
top10

100 100 100 100

                 Name Team Rating                         Career_best_rating
0         Trent Boult   NZ    726             770 v West Indies, 22/06/2019
1       Chris Woakes   ENG    700              711 v Sri Lanka, 04/07/2021
2     Josh Hazlewood   AUS    698                733 v England, 26/01/2018
3         Matt Henry    NZ    683             691 v Bangladesh, 26/03/2021
4   Mujeeb Ur Rahman   AFG    681                712 v Ireland, 24/01/2021
5     Jasprit Bumrah   IND    679            841 v West Indies, 01/11/2018
6     Shaheen Afridi   PAK    671              671 v Australia, 02/04/2022
7       Mehedi Hasan   BAN    661              725 v Sri Lanka, 25/05/2021
8    Shakib Al Hasan   BAN    657               717 v Zimbabwe, 05/11/2009
9        Rashid Khan   AFG    650               806 v Pakistan, 21/09/2018

<b>6) Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:      
a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.         
b) Top 10 women’s ODI Batting players along with the records of their team and rating.         
c) Top 10 women’s ODI all-rounder along with the records of their team and rating.</b>

a) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating.

In [15]:
#Sending get request to webpage server to get the source code of it
page=requests.get("https://www.icc-cricket.com/rankings/womens/team-rankings/odi")
page

#Webpage source code
page.content

#Parsing the source code by using BeautifulSoup and by html.parser
soup=BeautifulSoup(page.content,'html.parser')
soup

#Extracting all the tags having team names
team=soup.find_all('span',class_="u-hide-phablet")
team[:10]

#Extracting the text alone from the tags
teams=[]  #Empty list
for i in team:
    teams.append(i.get_text())
teams[:10]

#Extracting the tags having the number of matches for Rank1 team
match=soup.find_all('td',class_="rankings-block__banner--matches")
match

#Saving matches to matches list
Matches=[]  
for i in match:
    Matches.append(i.get_text().replace('\n',''))
Matches

#Extracting remaining matches
match=soup.find_all('td',class_="table-body__cell u-center-text")
match[:9]

del match[1::2]   #As it extracted other column data, we are deleting it

for i in match:
    Matches.append(i.get_text().replace('\n',''))
Matches[:10]

#Extracting the tags having the points for Rank1 team
points=soup.find_all('td',class_="rankings-block__banner--points")
points

#Saving points to points list
Points=[]  
for i in points:
    Points.append(i.get_text().replace('\n',''))
Points

#Extracting remaining points
points=soup.find_all('td',class_="table-body__cell u-center-text")
points[:9]

del points[::2]   #As other data are obtained, we are deleting them

#Saving points of respective teams
for i in points:
    Points.append(i.get_text().replace('\n',''))
Points[:10]

#Extracting the rating from tags of rank1 team
rating=soup.find_all('td',class_="rankings-block__banner--rating u-text-right")
rating

#Saving rating to rating list
Rating=[]  
for i in rating:
    Rating.append(i.get_text().replace('\n','').strip())
Rating

#Extracting other team ratings data
rating=soup.find_all('td',attrs={'class':'table-body__cell u-text-right rating'})
rating[:9]

#Saving other teams ratings 
for i in rating:
    Rating.append(i.get_text().replace('\n',''))
Rating=Rating[0:10]   #Saving only first 10 ratings
Rating

#Checking the length of each of the list obtained
print(len(teams),len(Matches),len(Points),len(Rating))

#Creating a new dataframe with the data we extracted
import pandas as pd
Team_Rankings=pd.DataFrame({})
Team_Rankings['Team']=teams[:10]
Team_Rankings['Matches']=Matches[:10]
Team_Rankings['Points']=Points[:10]
Team_Rankings['Rating']=Rating

#Checking the dataframe
Team_Rankings

15 10 10 10

           Team Matches Points Rating
0     Australia      29  4,837    167
1  South Africa      29  3,551    122
2       England      30  3,531    118
3         India      29  2,889    100
4   New Zealand      31  3,019     97
5   West Indies      30  2,768     92
6    Bangladesh      12    930     78
7      Pakistan      28  1,882     67
8     Sri Lanka       6    249     42
9      Zimbabwe       8      0      0

b) Top 10 ODI Batswomen in women along with the records of their team and rating.

In [16]:
#Sending get request to webpage server to get the source code of it
page=requests.get("https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting")
page

#Webpage source code
page.content

#Parsing the source code by using BeautifulSoup and by html.parser
soup=BeautifulSoup(page.content,'html.parser')
soup

#Extracting the tag having player name for Rank1
name=soup.find_all('div',class_="rankings-block__banner--name-large")
name

#Extracting the text alone from tag
names=[]  #Empty list
for i in name:
    names.append(i.get_text())
names

#Extracting the tag having player names
name=soup.find_all('td',class_="table-body__cell rankings-table__name name")
name[:9]

#Extracting the text from tags
for i in name:
    names.append(i.get_text().replace('\n', ' '))
names[:10]    

#Extracting the tag for team for rank1
team=soup.find_all('div',class_="rankings-block__banner--nationality")
team

#Extracting the text alone from tag
teams=[]  #Empty list
for i in team:
    teams.append(i.get_text().replace('\n', ''))
teams   

#Extracting the tags for other teams
team=soup.find_all('span',class_="table-body__logo-text")
team[:9]

#Extracting the text alone from tags
for i in team:
    teams.append(i.get_text())
teams[:10] 

#Extracting the tag having rating for rank1
rating=soup.find_all('div',class_="rankings-block__banner--rating")
rating

#Extracting the text alone from tag
ratings=[]  #Empty list
for i in rating:
    ratings.append(i.get_text())
ratings 

#Extracting the tag for ratings of other players
rating=soup.find_all('td',class_="table-body__cell rating")
rating[:9]

#Extracting the text alone from tags
for i in rating:
    ratings.append(i.get_text())
ratings[:10] 

#Extracting the tags having career best rating for rank1
career_best=soup.find_all('span',class_="rankings-block__career-best-text")
career_best

#Extracting the text alone from tag
career_best_rating=[]  #Empty list
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('  ',''))
career_best_rating    

#Extracting the tags for remaining players career best rating
career_best=soup.find_all('td',class_="table-body__cell u-text-right u-hide-phablet")
career_best[:9]

#Extracting the text alone from tags
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('                        ',' '))
career_best_rating[:10] 

#Checking the length of each of the list obtained
print(len(names),len(teams),len(ratings),len(career_best_rating))

#Creating a new dataframe with the data we extracted
import pandas as pd
top10=pd.DataFrame({})
top10['Name']=names[:10]
top10['Team']=teams[:10]
top10['Rating']=ratings[:10]
top10['Career_best_rating']=career_best_rating[:10]

#Checking the dataframe
top10

100 100 100 100

                  Name Team Rating                         Career_best_rating
0         Alyssa Healy  AUS    785                 785 v England, 03/04/2022
1      Natalie Sciver   ENG    750              750 v Australia, 03/04/2022
2         Beth Mooney   AUS    748                748 v England, 03/04/2022
3     Laura Wolvaardt    SA    722              741 v Australia, 22/03/2022
4         Meg Lanning   AUS    710            834 v New Zealand, 24/02/2016
5      Rachael Haynes   AUS    701            713 v West Indies, 15/03/2022
6         Mithali Raj   IND    686              839 v Australia, 24/12/2004
7   Amy Satterthwaite    NZ    681              756 v Australia, 02/03/2017
8     Smriti Mandhana   IND    669                797 v England, 28/02/2019
9      Tammy Beaumont   ENG    659                  791 v India, 27/06/2021

c) Top 10 women’s ODI all-rounders along with the records of their team and rating.

In [17]:
#Sending get request to webpage server to get the source code of it
page=requests.get("https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder")
page

#Webpage source code
page.content

#Parsing the source code by using BeautifulSoup and by html.parser
soup=BeautifulSoup(page.content,'html.parser')
soup

#Extracting the tag having player name for Rank1
name=soup.find_all('div',class_="rankings-block__banner--name-large")
name

#Extracting the text alone from tag
names=[]  #Empty list
for i in name:
    names.append(i.get_text())
names

#Extracting the tag having player names
name=soup.find_all('td',class_="table-body__cell rankings-table__name name")
name[:9]

#Extracting the text from tags
for i in name:
    names.append(i.get_text().replace('\n', ' '))
names[:10]    

#Extracting the tag for team for rank1
team=soup.find_all('div',class_="rankings-block__banner--nationality")
team

#Extracting the text alone from tag
teams=[]  #Empty list
for i in team:
    teams.append(i.get_text().replace('\n', ''))
teams   

#Extracting the tags for other teams
team=soup.find_all('span',class_="table-body__logo-text")
team[:9]

#Extracting the text alone from tags
for i in team:
    teams.append(i.get_text())
teams[:10] 

#Extracting the tag having rating for rank1
rating=soup.find_all('div',class_="rankings-block__banner--rating")
rating

#Extracting the text alone from tag
ratings=[]  #Empty list
for i in rating:
    ratings.append(i.get_text())
ratings 

#Extracting the tag for ratings of other players
rating=soup.find_all('td',class_="table-body__cell rating")
rating[:9]

#Extracting the text alone from tags
for i in rating:
    ratings.append(i.get_text())
ratings[:10] 

#Extracting the tags having career best rating for rank1
career_best=soup.find_all('span',class_="rankings-block__career-best-text")
career_best

#Extracting the text alone from tag
career_best_rating=[]  #Empty list
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('  ',''))
career_best_rating    

#Extracting the tags for remaining players career best rating
career_best=soup.find_all('td',class_="table-body__cell u-text-right u-hide-phablet")
career_best[:9]

#Extracting the text alone from tags
for i in career_best:
    career_best_rating.append(i.get_text().replace('\n', ' ').replace('                        ',' '))
career_best_rating[:10] 

#Checking the length of each of the list obtained
print(len(names),len(teams),len(ratings),len(career_best_rating))

#Creating a new dataframe with the data we extracted
import pandas as pd
top10=pd.DataFrame({})
top10['Name']=names[:10]
top10['Team']=teams[:10]
top10['Rating']=ratings[:10]
top10['Career_best_rating']=career_best_rating[:10]

#Checking the dataframe
top10

20 20 20 20

                 Name Team Rating                          Career_best_rating
0      Natalie Sciver  ENG    393                393 v Australia, 03/04/2022
1       Ellyse Perry   AUS    374             548 v West Indies, 11/09/2019
2     Marizanne Kapp    SA    359             419 v West Indies, 10/09/2021
3    Hayley Matthews    WI    338                   365 v India, 12/03/2022
4        Amelia Kerr    NZ    335            339 v South Africa, 17/03/2022
5   Ashleigh Gardner   AUS    269             279 v West Indies, 30/03/2022
6      Deepti Sharma   IND    249            397 v South Africa, 09/10/2019
7      Jess Jonassen   AUS    245             308 v West Indies, 11/09/2019
8    Katherine Brunt   ENG    221               296 v Australia, 03/02/2022
9     Jhulan Goswami   IND    217               308 v Australia, 02/02/2016

<b>7) Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world :     
i) Headline           
ii) Time         
iii) News Link</b>

In [18]:
page=requests.get('https://www.cnbc.com/world/?region=world')
page

soup=BeautifulSoup(page.content)
soup



headline=[]
for i in soup.find_all("a",class_="LatestNews-headline"):
    headline.append(i.text)
    
headline



time=[]
for i in soup.find_all("span",class_="LatestNews-wrapper"):
    time.append(i.text)
    
time



news_link=[]
for i in soup.find_all("div",class_="LatestNews-container"):
    news_link.append(i.find("a",class_="LatestNews-headline").get("href"))
news_link
print(len(news_link))

30

In [19]:
News_website_CNBC = pd.DataFrame({'Headline':headline,'Time':time, 'News_Link':news_link})
News_website_CNBC

,Headline,Time,News_Link
0,"Roughly 55% of U.S. say they are 'pro-choice,'...",19 Min Ago,https://www.cnbc.com/2022/06/02/roe-v-wade-rou...
1,Stocks making the biggest moves midday: Micros...,20 Min Ago,https://www.cnbc.com/2022/06/02/stocks-making-...
2,Harvey Weinstein's sex crime convictions uphel...,34 Min Ago,https://www.cnbc.com/2022/06/02/harvey-weinste...
3,UBS downgrades lithium name Albemarle after 35...,54 Min Ago,https://www.cnbc.com/2022/06/02/ubs-downgrades...
4,Options traders bet on big move for Lululemon ...,59 Min Ago,https://www.cnbc.com/2022/06/02/options-trader...
5,These defensive stocks can protect you from st...,1 Hour Ago,https://www.cnbc.com/2022/06/02/these-defensiv...
6,Winklevoss twins' Gemini cutting 10% of its st...,1 Hour Ago,https://www.cnbc.com/2022/06/02/winklevoss-twi...
7,The energy in nuclear waste could power the U....,1 Hour Ago,https://www.cnbc.com/2022/06/02/nuclear-waste-...
8,New CNN boss has a message for staffers: Cool ...,1 Hour Ago,https://www.cnbc.com/2022/06/02/new-cnn-boss-h...
9,Amazon to shut down Kindle store in China,2 Hours Ago,https://www.cnbc.com/2022/06/02/amazon-to-shut...
10,U.S. goes after more Russian yachts linked to ...,2 Hours Ago,https://www.cnbc.com/2022/06/02/us-goes-after-...
11,Ray Dalio: Going broke ‘was one of the best th...,2 Hours Ago,https://www.cnbc.com/2022/06/02/ray-dalio-goin...
12,How to pay for college after a financial setback,2 Hours Ago,https://www.cnbc.com/2022/06/02/how-to-pay-for...
13,Find stability in this turbulent market – and ...,2 Hours Ago,https://www.cnbc.com/2022/06/02/these-stocks-o...
14,Dow is attempting a rebound. Here are Wall Str...,3 Hours Ago,https://www.cnbc.com/2022/06/02/these-are-wall...
15,How this 34-year-old balanced a now six-figure...,3 Hours Ago,https://www.cnbc.com/2022/06/02/how-to-balance...
16,Fed Vice Chair Brainard says it's hard to see ...,3 Hours Ago,https://www.cnbc.com/2022/06/02/fed-vice-chair...
17,Starbucks union creates $1 million fund to cov...,3 Hours Ago,https://www.cnbc.com/2022/06/02/starbucks-unio...
18,Do Kwon unlikely to face prison for $60 billio...,3 Hours Ago,https://www.cnbc.com/2022/06/02/could-do-kwon-...
19,'I work just 2 hours a day': 24-year-old who m...,3 Hours Ago,https://www.cnbc.com/2022/06/02/24-year-old-wh...
20,Constance Wu: New grads should see ‘failure as...,4 Hours Ago,https://www.cnbc.com/2022/06/02/constance-wu-g...
21,What Cramer is watching Thursday — Chewy soars...,4 Hours Ago,https://www.cnbc.com/2022/06/02/cramer-thursda...
22,Tiger Global drops 14% in May during the bruta...,4 Hours Ago,https://www.cnbc.com/2022/06/02/tiger-global-d...
23,"Microsoft cuts fourth-quarter guidance, cites ...",4 Hours Ago,https://www.cnbc.com/2022/06/02/microsoft-lowe...
24,"Angela Merkel breaks silence on Ukraine, calls...",4 Hours Ago,https://www.cnbc.com/2022/06/02/angela-merkel-...
25,Ford's U.S. sales fell just 4.5% in May amid h...,4 Hours Ago,https://www.cnbc.com/2022/06/02/fords-us-sales...
26,The market wants a soft landing for the econom...,4 Hours Ago,https://www.cnbc.com/2022/06/02/the-market-wan...
27,"Ford to add over 6,000 U.S. jobs to build more...",4 Hours Ago,https://www.cnbc.com/2022/06/02/ford-to-add-ov...
28,Amazon is 'obstructing' probe into deadly ware...,4 Hours Ago,https://www.cnbc.com/2022/06/02/amazon-obstruc...
29,Why hydropower is the forgotten giant of clean...,4 Hours Ago,https://www.cnbc.com/2022/06/02/why-hydropower...

<b>8) Write a python program to scrape the details of most downloaded articles from AI in last 90 days.
https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles
Scrape below mentioned details :         
i) Paper Title        
ii) Authors         
iii) Published Date      
iv) Paper URL</b>

In [20]:
page=requests.get('https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles')
page

soup=BeautifulSoup(page.content)
soup



paper_title=[]
for i in soup.find_all("h2",class_="sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR"):
    paper_title.append(i.text)
    
paper_title



authors=[]
for i in soup.find_all("span",class_="sc-1w3fpd7-0 pgLAT"):
    authors.append(i.text)
    
authors



published_date=[]
for i in soup("span",class_="sc-1thf9ly-2 bKddwo"):
    published_date.append(i.text)

published_date



paper_url=[]
for i in soup.find_all("li",class_="sc-9zxyh7-1 sc-9zxyh7-2 exAXfr jQmQZp"):
    paper_url.append(i.find("a",class_="sc-5smygv-0 nrDZj").get("href"))
    
paper_url

['https://www.sciencedirect.com/science/article/pii/S0004370221000862',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000722',
 'https://www.sciencedirect.com/science/article/pii/S0004370215000910',
 'https://www.sciencedirect.com/science/article/pii/S0004370298000551',
 'https://www.sciencedirect.com/science/article/pii/S0004370216300790',
 'https://www.sciencedirect.com/science/article/pii/S0004370218305988',
 'https://www.sciencedirect.com/science/article/pii/S0004370220301855',
 'https://www.sciencedirect.com/science/article/pii/S0004370214001386',
 'https://www.sciencedirect.com/science/article/pii/S0004370299000521',
 'https://www.sciencedirect.com/science/article/pii/S0004370219300116',
 'https://www.sciencedirect.com/science/article/pii/S0004370220301533',
 'https://www.sciencedirect.com/science/article/pii/S0004370207000793',
 'https://www.sciencedirect.com/science/article/pii/S0004370216300285',
 'https://www.sciencedirect.com/science/article/pii/S0004370220301958',
 'https://www.sciencedirect.com/science/article/pii/S0004370297000635',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000515',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000539',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000096',
 'https://www.sciencedirect.com/science/article/pii/S0004370216300868',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000588',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000102',
 'https://www.sciencedirect.com/science/article/pii/S0004370213001082',
 'https://www.sciencedirect.com/science/article/pii/S000437029700043X',
 'https://www.sciencedirect.com/science/article/pii/S0004370221000734',
 'https://www.sciencedirect.com/science/article/pii/S0004370209001398']

In [21]:
Most_downloaded_article=pd.DataFrame({'Paper Title':paper_title,'Authors':authors,'Published Date':
                                     published_date,'Paper URL':paper_url})

Most_downloaded_article

,Paper Title,Authors,Published Date,Paper URL
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021,https://www.sciencedirect.com/science/article/...
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021,https://www.sciencedirect.com/science/article/...
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015,https://www.sciencedirect.com/science/article/...
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998,https://www.sciencedirect.com/science/article/...
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017,https://www.sciencedirect.com/science/article/...
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019,https://www.sciencedirect.com/science/article/...
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021,https://www.sciencedirect.com/science/article/...
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015,https://www.sciencedirect.com/science/article/...
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999,https://www.sciencedirect.com/science/article/...
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020,https://www.sciencedirect.com/science/article/...
10,Evaluating XAI: A comparison of rule-based and...,"van der Waa, Jasper, Nieuwburg, Elisabeth, Cre...",February 2021,https://www.sciencedirect.com/science/article/...
11,Argumentation in artificial intelligence,"Bench-Capon, T.J.M., Dunne, Paul E.",October 2007,https://www.sciencedirect.com/science/article/...
12,Algorithms for computing strategies in two-pla...,"Bošanský, Branislav, Lisý, Viliam and 3 more",August 2016,https://www.sciencedirect.com/science/article/...
13,Multiple object tracking: A literature review,"Luo, Wenhan, Xing, Junliang and 4 more",April 2021,https://www.sciencedirect.com/science/article/...
14,Selection of relevant features and examples in...,"Blum, Avrim L., Langley, Pat",December 1997,https://www.sciencedirect.com/science/article/...
15,A survey of inverse reinforcement learning: Ch...,"Arora, Saurabh, Doshi, Prashant",August 2021,https://www.sciencedirect.com/science/article/...
16,Explaining individual predictions when feature...,"Aas, Kjersti, Jullum, Martin, Løland, Anders",September 2021,https://www.sciencedirect.com/science/article/...
17,A review of possible effects of cognitive bias...,"Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Joha...",June 2021,https://www.sciencedirect.com/science/article/...
18,Integrating social power into the decision-mak...,"Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.",December 2016,https://www.sciencedirect.com/science/article/...
19,“That's (not) the output I expected!” On the r...,"Riveiro, Maria, Thill, Serge",September 2021,https://www.sciencedirect.com/science/article/...
20,Explaining black-box classifiers using post-ho...,"Kenny, Eoin M., Ford, Courtney, Quinn, Molly, ...",May 2021,https://www.sciencedirect.com/science/article/...
21,Algorithm runtime prediction: Methods & evalua...,"Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyto...",January 2014,https://www.sciencedirect.com/science/article/...
22,Wrappers for feature subset selection,"Kohavi, Ron, John, George H.",December 1997,https://www.sciencedirect.com/science/article/...
23,Commonsense visual sensemaking for autonomous ...,"Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srik...",October 2021,https://www.sciencedirect.com/science/article/...
24,"Quantum computation, quantum theory and AI","Ying, Mingsheng",February 2010,https://www.sciencedirect.com/science/article/...

<b>9) Write a python program to scrape mentioned details from dineout.co.in :      
i) Restaurant name    
ii) Cuisine         
iii) Location     
iv) Ratings       
v) Image URL</b>

In [22]:
page=requests.get('https://www.dineout.co.in/delhi-restaurants?search_str=Restaurant')
page

soup=BeautifulSoup(page.content)
soup

restaurant=[]
for i in soup.find_all("div", class_="restnt-info cursor"):
    restaurant.append(i.text[:-30])
    
location=[]
for i in soup.find_all("div", class_="restnt-loc ellipsis"):
    location.append(i.text)
    
rating=[]
for i in soup.find_all("div",class_="restnt-rating rating-4"):
    rating.append(i.text)
    
cuisine=[]
for i in soup.find_all("span",class_="double-line-ellipsis"):
    cuisine.append(i.text.split("|")[1]) 
    
image=[]
for i in soup.find_all("div",class_="img-wrap"):
    image.append(i.find("img",class_="no-img").get("data-src"))

In [23]:
Dineout=pd.DataFrame({'Restaurant Name':restaurant,'Cuisine':cuisine,'Location':location,'Ratings':rating,'Image URL':image})
Dineout

,Restaurant Name,Cuisine,Location,Ratings,Image URL
0,Tamasha,"Continental, Asian, Italian, North Indian","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
1,"LocalScindia House,","North Indian, Asian, Continental","Scindia House,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
2,Unplugged Courtyard,"North Indian, Italian, Chinese, Turkish, Cont...","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
3,"The G.T. ROADM-Block,",North Indian,"M-Block,Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
4,Warehouse Cafe,"North Indian, Chinese, Italian","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
5,Ardor 2.1 Restaurant and Lounge,"North Indian, Chinese, Italian, Continental","Connaught Place, Central Delhi",3.8,https://im1.dineout.co.in/images/uploads/resta...
6,Connaught Clubhouse Microbrewery,"North Indian, Continental, Asian, Chinese","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
7,High 5 - Everyday Wholesale Bar,"North Indian, Continental, Chinese","Connaught Place, Central Delhi",3.9,https://im1.dineout.co.in/images/uploads/resta...
8,"Ministry Of BeerM-Block,","North Indian, Continental, American, Asian","M-Block,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
9,The Junkyard Cafe,"North Indian, Continental, Chinese, Fast Food","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
10,QBA,"North Indian, Continental, Italian","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
11,Somewhere Restaurant & Bar,"North Indian, Continental, Asian","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
12,"Kwality RestaurantRegal Cinema Complex,","North Indian, Continental, Mughlai","Regal Cinema Complex,Connaught Place, Central ...",4.4,https://im1.dineout.co.in/images/uploads/resta...
13,Ghoomar Traditional Thali Restaurant,"North Indian, Rajasthani","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
14,Lord of the Drinks,"Chinese, North Indian, Fast Food","Connaught Place, Central Delhi",4.2,https://im1.dineout.co.in/images/uploads/resta...
15,"Oh My GodF-Block,","Continental, North Indian, Chinese","F-Block,Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...
16,Openhouse Cafe,"North Indian, Asian, Italian","Connaught Place, Central Delhi",4.1,https://im1.dineout.co.in/images/uploads/resta...
17,Berco's,"Chinese, Thai","Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
18,"Chili's American Grill and BarM-Block,","Mexican, American, Tex Mex","M-Block,Connaught Place, Central Delhi",4.3,https://im1.dineout.co.in/images/uploads/resta...
19,My Bar Square,"Finger Food, Chinese, Continental, Italian","Connaught Place, Central Delhi",3.8,https://im1.dineout.co.in/images/uploads/resta...
20,Sandoz,"North Indian, Chinese, Continental","Connaught Place, Central Delhi",4,https://im1.dineout.co.in/images/uploads/resta...

<b>10) Write a python program to scrape the details of top publications from Google Scholar from
https://scholar.google.com/citations?view_op=top_venues&hl=en     
i) Rank          
ii) Publication       
iii) h5-index      
iv) h5-median</b>

In [24]:
page=requests.get('https://scholar.google.com/citations?view_op=top_venues&hl=en')
page

soup=BeautifulSoup(page.content)
soup

rank=[]
for i in soup.find_all("td",class_="gsc_mvt_p"):
    rank.append(i.text)
    
publication=[]
for i in soup("td",class_="gsc_mvt_t"):
    publication.append(i.text)
    
index=[]
for i in soup.find_all("td",class_="gsc_mvt_n"):
    index.append(i.text)

    
index_a=index[0::2] 

median=index[1::2]

In [25]:
Detail_of_top_publication=pd.DataFrame({"Rank":rank,"Publication":publication,"H5 Index":index_a,"H5 Median":median})
Detail_of_top_publication

    Rank                                        Publication H5 Index H5 Median
0     1.                                             Nature      414       607
1     2.                The New England Journal of Medicine      410       704
2     3.                                            Science      391       564
3     4.  IEEE/CVF Conference on Computer Vision and Pat...      356       583
4     5.                                         The Lancet      345       600
..   ...                                                ...      ...       ...
95   96.                            Frontiers in Immunology      134       177
96   97.                                              Small      134       173
97   98.                                  Nature Immunology      133       210
98   99.                                      JAMA Oncology      133       202
99  100.                               The Lancet Neurology      133       200

[100 rows x 4 columns]